### ISSUE TITLE
Group column resize broken

### ISSUE THREAD

**Issue by Techn1x** [adopted-ember-addons/ember-light-table#498]
I have `resizable: true` on my group columns, and the resizer appears etc. but when I drag to resize it, the columns don't change size. Draggable works though.

`resizable: true` works correctly on my subColumns, and resizes the group columns correctly.

I noticed this merged PR from over a year ago which seems to suggest that it should work
https://github.com/offirgolan/ember-light-table/pull/252

So I think this might be a regression

**Comment by alexander-alvarez** [comment]
@Techn1x  thanks for reporting this, and sorry this isn't working
I unfortunately don't have any familiarity with this piece of code, so it may take some time to investigate and resolve it. 

Realistically, it may take till this coming weekend or next for me to dive into it

**Comment by Techn1x** [comment]
No problem, it's not critical for my tables :)
