### ISSUE TITLE
Labels change with breakpoints

### ISSUE THREAD

**Issue by Techn1x** [adopted-ember-addons/ember-light-table#505]
It would be great if I could specify a column header label to use at each breakpoint. For example "Current Pressure (PSI)" is fine for desktop views, but down at mobile width that's some valuable space being used up for a label that could easily just be "Pressure"

The current workaround I guess is to define 2 columns that are exactly the same, apart from the breakpoints that they appear at and their labels, but this seems superfluous

Perhaps something like this would be good;
```javascript
{
  label: "Current Pressure (PSI)", // Used for any breakpoints that don't have a label defined
  valuePath: 'pressure',
  resizable: true,
  draggable: true,
  breakpoints: {
    'mobile': {
      label: 'Pressure'
    },
    'tablet': {
      label: 'Pressure (PSI)'
    },
    'desktop': {
      label: 'Current Pressure (PSI)'
    }
  }
}
```

Once this is working, we could work towards allowing this structure to then be used to define/replace other column properties at each breakpoint.

Just an idea for a future feature.

**Comment by alexander-alvarez** [comment]
Another way to implement this would be to write  custom column type / component, one where
it leverages the `media` service to hook into the different responsive breakpoints
`this.get('media.isMobile');` (see https://github.com/freshbooks/ember-responsive)

Then you could write a computed property that reads from an object similar to what you did above.

^ I'd be curious to see how ergonomic this is for your usecase (instead of the separate columns)

**Comment by Techn1x** [comment]
Ah thanks, that works quite well!

For anyone else wanting this, here's how I did it;
```javascript
{
  label: "Current Pressure (PSI)", // Used for any breakpoints that don't have a label defined
  valuePath: 'pressure',
  resizable: true,
  draggable: true,
  type: 'custom-column',
  breakpointOverrides: {
    'mobile': {
      label: 'Pressure'
    },
    'tablet': {
      label: 'Pressure (PSI)'
    },
    'desktop': {
      label: 'Current Pressure (PSI)'
    }
  }
}
```

```javascipt
//app/components/light-table/custom-column.js
import { computed } from '@ember/object';
import { inject as service } from '@ember/service';

import Column from 'ember-light-table/components/columns/base';

export default Column.extend({
	screenSize: service(),  // This is my own screen size service implementation, instead of ember-responsive... one day I should replace this with ember-responsive
	
	label: computed('column.label','column.breakpointOverrides','screenSize.getSizeClass', function() {
		let sizeClass = this.get('screenSize.getSizeClass');
		let breakpointLabel = this.get('column.breakpointOverrides.'+sizeClass+'.label');
		if(breakpointLabel)	return breakpointLabel;
		return this.get('column.label');
	})
});
```

If I also wanted to override say the column's `format` attribute per breakpoint, how would I go about that? I tried a similar approach with no luck.

**Comment by Techn1x** [comment]
While this approach is great and works for `label`, I keep wanting to override more column fields at each breakpoint (like `format` and `width`) but it seems to be more complicated than I thought to do these

**Comment by buschtoens** [comment]
I also wrote a custom column type, that switches between two (or more) `valuePath`s on click. Maybe a more general approach—not only for media breakpoints—for changing column properties would be better suited.
