### ISSUE TITLE
Transferring to adopted-ember-addons

### ISSUE THREAD

**Issue by rwwagner90** [adopted-ember-addons/ember-light-table#728]
Hi @offirgolan, what would you think about transferring this to https://github.com/adopted-ember-addons so that more community members could jump in and help maintain it?

**Comment by offirgolan** [comment]
Im ok with that unless any of the current maintainers object.

**Comment by rwwagner90** [comment]
@buschtoens @alexander-alvarez @snewcomer any objections?

**Comment by snewcomer** [comment]
zilch.  Great idea!

**Comment by offirgolan** [comment]
@rwwagner90 whats the process for transferring the repo over?

**Comment by rwwagner90** [comment]
@offirgolan there is a checklist here https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md

I have not added myself to the list there, but please add me as a maintainer on npm as well, I am rwwagner90 everywhere.

**Comment by rwwagner90** [comment]
@offirgolan can you make me an admin of the repo and give me permissions on npm? After that, I can transfer it over.

**Comment by maxwondercorn** [comment]
Any movement on the process to move ELT to adopted-ember-addons?

**Comment by rwwagner90** [comment]
CC @offirgolan ^

**Comment by rwwagner90** [comment]
Done and transferred!
