### ISSUE TITLE
404 http://offirgolan.github.io/

### ISSUE THREAD

**Issue by yaxinr** [adopted-ember-addons/ember-light-table#750]

**Comment by godric3** [comment]
http://adopted-ember-addons.github.io/ember-light-table/ works, but should be changed in repo about section(and other places that references old repo)

**Comment by Gorzas** [comment]
I've create a PR with the changes but I haven't permissions to update the link in the about section :sweat_smile: .

**Comment by Alonski** [comment]
Just updated it. Thanks
